data:extend(
{
  {
    type = "fluid",
    name = "nitric-acid",
    default_temperature = 25,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0.75, b=0.25},
    flow_color = {r=0.5, g=0.5, b=0.5},
    icon = "__It's Scientific!__/graphics/icons/fluid/nitric-acid.png",
    order = "a[fluid]-a[nitric-acid]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "dissolved-iron",
    default_temperature = 25,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.34, b=0.6},
    flow_color = {r=0.3, g=0.45, b=0.5},
    icon = "__It's Scientific!__/graphics/icons/fluid/dissolved-iron.png",
    order = "a[fluid]-a[dissolved-iron]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "dissolved-copper",
    default_temperature = 25,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.34, b=0.6},
    flow_color = {r=0.8, g=0.3, b=0.1},
    icon = "__It's Scientific!__/graphics/icons/fluid/dissolved-copper.png",
    order = "a[fluid]-a[dissolved-copper]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "dissolved-lead",
    default_temperature = 25,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.34, b=0.6},
    flow_color = {r=0.4, g=0.2, b=0.5},
    icon = "__It's Scientific!__/graphics/icons/fluid/dissolved-lead.png",
    order = "a[fluid]-a[dissolved-lead]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "dissolved-gold",
    default_temperature = 25,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.34, b=0.6},
    flow_color = {r=1, g=0.9, b=0.2},
    icon = "__It's Scientific!__/graphics/icons/fluid/dissolved-gold.png",
    order = "a[fluid]-a[dissolved-gold]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "nitrogen",
    default_temperature = 0,
    max_temperature = 100,
    heat_capacity = "0.25KJ",
    base_color = {r=0.1, g=0.4, b=1},
    flow_color = {r=0.75, g=0.75, b=0.75},
    icon = "__It's Scientific!__/graphics/icons/fluid/nitrogen.png",
    order = "a[fluid]-a[nitrogen]",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "oxygen",
    default_temperature = 0,
    max_temperature = 100,
    heat_capacity = "0.25KJ",
    base_color = {r=1, g=0.1, b=0.4},
    flow_color = {r=0.75, g=0.75, b=0.75},
    icon = "__It's Scientific!__/graphics/icons/fluid/oxygen.png",
    order = "a[fluid]-a[oxygen]",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "argon",
    default_temperature = 0,
    max_temperature = 100,
    heat_capacity = "0.25KJ",
    base_color = {r=0.3, g=0.9, b=1},
    flow_color = {r=0.75, g=0.75, b=0.75},
    icon = "__It's Scientific!__/graphics/icons/fluid/argon.png",
    order = "a[fluid]-a[argon]",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "liquid-air",
    default_temperature = 0,
    max_temperature = 100,
    heat_capacity = "0.25KJ",
    base_color = {r=0.8, g=0.9, b=1},
    flow_color = {r=0.75, g=0.75, b=0.75},
    icon = "__It's Scientific!__/graphics/icons/fluid/liquid-air.png",
    order = "a[fluid]-a[liquid-air]",
    pressure_to_speed_ratio = 0.2,
    flow_to_energy_ratio = 0.59,
  }
})
